---
# Usage: http://ruhoh.com/usage/configure/ 

RuhohSpec: '1.0'
theme : twitter
production_url : http://zx1986.ruhoh.com

posts:
  permalink: /:filename
  summary_lines: 2000
  latest: 1

pages:
  permalink: 'pretty'
